export const data = `
scalar DateTime

type User{
    id: ID!
    name: String! ## we get it with user in  firebase section with metadata
    email: String! ## we get it with user in  firebase section with metadata
    password: String! ## we get it with user in  firebase section with metadata
    createdDate: DateTime ## we get it with user in  firebase section with metadata
    lateSign: DateTime ## we get it with user in  firebase section with metadata
    avatar: String ## we get it with user in  firebase section with metadata
    country: String
    city: String
}

## --------- User Inputs ---------
input UserInput{
    name: String! 
    email: String! 
    password: String! 
    avatar: String
    country: String
    city: String
}

enum EnumOrderBy{
    createdDate
    city
    country
}
extend type Query{
    users(whereID: ID, orderBy:EnumOrderBy): [User]!
}
extend type Mutation{
    createUser(data: UserInput!): ID!
}
`